### ISSUE TITLE
cluster_AmazonEKSClusterPolicy always changing

### ISSUE THREAD

**Issue by bilalbayasut** [terraform-aws-modules/terraform-aws-eks#1248]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [x] kudos, thank you, warm fuzzy

## What is the current behavior?
I have node_group set and everytime I made changes, the policies are always changing
```
# module.k8s.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSClusterPolicy" {
      ~ id         = "cluster-name20210216185206327200000001-20210217180909569600000006" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

  # module.k8s.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSServicePolicy" {
      ~ id         = "cluster-name20210216185206327200000001-20210217180909465800000001" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

  # module.k8s.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSVPCResourceControllerPolicy" {
      ~ id         = "cluster-name20210216185206327200000001-20210217180909476200000002" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

  # module.k8s.module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "workers_AmazonEC2ContainerRegistryReadOnly" {
      ~ id         = "cluster-name20210216193254425800000004-20210217180909530300000005" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

  # module.k8s.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "workers_AmazonEKSWorkerNodePolicy" {
      ~ id         = "cluster-name20210216193254425800000004-20210217180909476700000003" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

  # module.k8s.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "workers_AmazonEKS_CNI_Policy" {
      ~ id         = "cluster-name20210216193254425800000004-20210217180909530100000004" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy" -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }```
```

I know this maybe not harmful , but this of course will distract our output to see which resources will be applied. my question is how to remove these unnecessary update.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
resource "aws_iam_role" "tf-eks-master" {
  name = "terraform-eks-cluster"
  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}
resource "aws_iam_role_policy_attachment" "tf-cluster-AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.tf-eks-master.name
}
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  version                         = "13.2.1"
  cluster_name                    = var.cluster_name
  cluster_version                 = "1.18"
  subnets                         = var.subnets
  cluster_endpoint_private_access = true
  create_eks                      = var.create_eks
  vpc_id                          = var.vpc_id

  # If manage_cluster_iam_resources set to false, cluster_iam_role_name must be specified.
   manage_cluster_iam_resources = false
  cluster_iam_role_name        = aws_iam_role.tf-eks-master.name

  # manage_worker_iam_resources     = false

  node_groups_defaults = {
    ami_type = "AL2_x86_64"
  }

  node_groups = {
    eks_nodes = {
      desired_capacity = var.desired_capacity
      max_capacity     = var.max_capacity
      min_capacity     = var.min_capacity
      instance_type    = var.instance_type
      platform         = "linux"
    }
  }

  map_roles          = local.map_roles
  map_users          = var.map_users
  map_accounts       = var.map_accounts
  write_kubeconfig   = true
  config_output_path = "./"
}
```

## What's the expected behavior?

the expected would be no changes in the policies for this cluster and worker groups as no changes made.

## Are you able to fix this problem and submit a PR? Link here if you have already.
tried hard, but not working

## Environment details

* Affected module version:
* OS: ubuntu
* Terraform version:   required_version = ">=0.14.4"

**Comment by rogersd** [comment]
I'm having the same issue, and it can result in the EKS roles not having any policies attached if the run fails partway through.

```
  # module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSClusterPolicy" {
      ~ id         = "cluster-name20210108190934192900000003-20210219181755612200000005" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy" -> (known after apply) # forces replacement
        role       = "cluster-name20210108190934192900000003"
    }

  # module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSServicePolicy" {
      ~ id         = "cluster-name20210108190934192900000003-20210219181755612700000006" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy" -> (known after apply) # forces replacement
        role       = "cluster-name20210108190934192900000003"
    }

  # module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "cluster_AmazonEKSVPCResourceControllerPolicy" {
      ~ id         = "cluster-name20210108190934192900000003-20210219181755609600000004" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController" -> (known after apply) # forces replacement
        role       = "cluster-name20210108190934192900000003"
    }

  # module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "workers_AmazonEC2ContainerRegistryReadOnly" {
      ~ id         = "cluster-name20210108192408979100000009-20210219181755578700000003" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly" -> (known after apply) # forces replacement
        role       = "cluster-name20210108192408979100000009"
    }

  # module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "workers_AmazonEKSWorkerNodePolicy" {
      ~ id         = "cluster-name20210108192408979100000009-20210219181755572500000002" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy" -> (known after apply) # forces replacement
        role       = "cluster-name20210108192408979100000009"
    }

  # module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0] must be replaced
+/- resource "aws_iam_role_policy_attachment" "workers_AmazonEKS_CNI_Policy" {
      ~ id         = "cluster-name20210108192408979100000009-20210219181755521900000001" -> (known after apply)
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy" -> (known after apply) # forces replacement
        role       = "cluster-name20210108192408979100000009"
    }
```

My config:

```
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  cluster_name                    = var.eks_cluster_name
  cluster_version                 = var.cluster_version
  subnets                         = var.vpc_subnets
  vpc_id                          = var.vpc_id
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true

  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]

  worker_groups_launch_template = [
    {
      name                                     = "1"
      instance_type                            = var.instance_types[0]
      override_instance_types                  = var.instance_types
      asg_max_size                             = var.asg_max_size
      asg_min_size                             = var.asg_min_size
      asg_desired_capacity                     = var.asg_desired_capacity
      on_demand_base_capacity                  = var.asg_desired_capacity
      on_demand_percentage_above_base_capacity = 100
      kubelet_extra_args                       = "--node-labels=node.kubernetes.io/lifecycle=normal"
      root_encrypted                           = true
      root_volume_size                         = var.root_volume_size
      root_volume_type                         = "gp3"
      max_instance_lifetime                    = var.max_instance_lifetime
    },
  ]

  map_roles = [
    {
      rolearn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.iam_roles[0]}"
      username = "{{SessionName}}"
      groups   = ["system:masters"]
    },
    {
      rolearn  = aws_iam_role.service.arn
      username = "service"
      groups   = ["system:masters"]
    }
  ]

  tags = {
    env = var.environment
  }
}
```

**Comment by rogersd** [comment]
It's also doing the creation and then deleting what it creates, requiring a second run to restore the role policy attachment:

```
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]: Creating...
module.cluster.module.eks_cluster.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]: Creating...
```

**Comment by rogersd** [comment]
Possibly related to the partition being a computed value? https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_partition.go

**Comment by rogersd** [comment]
@barryib any chance we can get you to take a look at this?

**Comment by felipeac** [comment]
@rogersd I've been facing the same issue. Always requires a second run to restore the role policy attachment.

**Comment by jrsdav** [comment]
I was experimenting with the new `default_tags` AWS provider configuration in version 3.38.0 and discovered that if I have churn from dynamic/computed tag values somewhere in the module where I'm also using the `terraform-aws-modules/eks` module (for instance, a tag in the VPC resource that the EKS module depends on), it will trigger a refresh on a bunch of different things in the EKS module.

I can test this by adding or removing a tag (or just using a computed value at execution time like `timestamp()`)  to the VPC resource where the EKS module has an explicitly depends on. So for instance, given the following (abridged) configuration:

```hcl
terraform {
  required_version = ">=0.15"

  required_providers {
    aws = {
      version = ">= 3.38.0"
      source  = "hashicorp/aws"
    }
  }
}

provider "aws" {}

resource "aws_vpc" "vpc" {
  cidr_block           = var.vpc_cidr

  tags = {
    test = timestamp()          // This computed value is what will cause churn in the EKS module
  }
}

module "eks" {
  source = "terraform-aws-modules/eks/aws"
  version = "16.2.0"
  cluster_name = local.cluster_name
  cluster_version = var.cluster_version
  subnets = local.cluster_subnets
  vpc_id = aws_vpc.vpc.id
  write_kubeconfig = true
  enable_irsa = true
  config_output_path = pathexpand("~/.kube/${local.cluster_name}-config")
  cluster_iam_role_name = "${local.cluster_name}-role"
  manage_cluster_iam_resources = true
  manage_worker_iam_resources  = false

  depends_on = [
    aws_vpc.vpc          // Churn only occurs if depends_on is declared
  ]
}
```

Every time `time = timestamp()` computes a new value, it will cause the EKS module to churn on the following resources **during the first `terraform plan`**:

```hcl

  # aws_vpc.vpc will be updated in-place
  ~ resource "aws_vpc" "vpc" {
        id                               = "vpc-1234567890"
      ~ tags                             = {
          - "test" = "2021-05-26T17:38:10Z"
        } -> (known after apply)
      ~ tags_all                         = {
          - "test" = "2021-05-26T17:38:10Z"
        } -> (known after apply)
        # (14 unchanged attributes hidden)
    }

  # module.eks.data.aws_caller_identity.current will be read during apply
  # (config refers to values not yet known)

  # module.eks.data.aws_iam_policy_document.cluster_assume_role_policy
  # (config refers to values not yet known)

  # module.eks.data.aws_iam_policy_document.cluster_elb_sl_role_creation[0]
  # (config refers to values not yet known)

  # module.eks.data.aws_iam_policy_document.workers_assume_role_policy will be read during apply
  # (config refers to values not yet known)

  # module.eks.data.aws_partition.current will be read during apply
  # (config refers to values not yet known)

  # module.eks.data.http.wait_for_cluster[0] will be read during apply
  # (config refers to values not yet known)

  # module.eks.aws_iam_openid_connect_provider.oidc_provider[0] must be replaced
      ~ client_id_list  = [
          - "sts.amazonaws.com",
        ] -> (known after apply) # forces replacement

 # module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0] will be updated in-place

 # module.eks.aws_iam_role.cluster[0] will be updated in-place

 # module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0] must be replaced
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy" -> (known after apply) # forces replacement

  # module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0] must be replaced
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy" -> (known after apply) # forces replacement

  # module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0] must be replaced
      ~ policy_arn = "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController" -> (known after apply) # forces replacement
 ```
 
 And this is what follows **from a subsequent `terraform plan`**:
 
```hcl

  # aws_vpc.vpc will be updated in-place
  ~ resource "aws_vpc" "vpc" {
        id                               = "vpc-1234567890"
      ~ tags                             = {
          - "test" = "2021-05-26T17:48:40Z"
        } -> (known after apply)
      ~ tags_all                         = {
          - "test" = "2021-05-26T17:48:40Z"
        } -> (known after apply)
        # (14 unchanged attributes hidden)
    }

  # module.eks.data.aws_caller_identity.current will be read during apply
  # (config refers to values not yet known)

  # module.eks.data.aws_iam_policy_document.cluster_assume_role_policy
  # (config refers to values not yet known)

  # module.eks.data.aws_iam_policy_document.cluster_elb_sl_role_creation[0]
  # (config refers to values not yet known)

  # module.eks.data.aws_iam_policy_document.workers_assume_role_policy will be read during apply
  # (config refers to values not yet known)

  # module.eks.data.aws_partition.current will be read during apply
  # (config refers to values not yet known)

  # module.eks.data.http.wait_for_cluster[0] will be read during apply
  # (config refers to values not yet known)

  # module.eks.aws_iam_openid_connect_provider.oidc_provider[0] must be replaced
      ~ client_id_list  = [
          - "sts.amazonaws.com",
        ] -> (known after apply) # forces replacement

 # module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0] will be updated in-place

 # module.eks.aws_iam_role.cluster[0] will be updated in-place

 # module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0] will be created

 # module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0] will be created

  # module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0] will be created
```

It never rectifies, and my applies will always be stuck in this "double-apply" cycle in order to get things working properly. 

I should mention, adding `lifecycle { ignore_changes = [ tags ] }` to my VPC resource will stop this. But I assume the problem will be present on any resource that the EKS module has an explicit `depends_on` declared, in particular if the underlying dependency has a computed change during a plan/apply.

**Comment by zerog2k** [comment]
We are having a similar issue and suspect that it's something to do with IAM eventual consistency, i.e. immediately removing a managed policy attachment, then adding it back. (Observed there was about 5 seconds between destroy and create in our tf apply logs, but appears that create was "lost" on the resource.)
This is just a hunch based upon some other mentions of IAM eventual consistency.

As to the trigger chain, more conjecture:
The first, unexpected part (at least for us) here is that mutation/addition of tags on a parent resource cause "churn" as noted here. I can somewhat see this as logical as some tags (like "Name") might affect data sources, i.e. where they are filtering on tags. 
The next part is that the dreaded only "known after apply" behavior w.r.t. computed data sources is causing this to be replaced because of the interpolated managed policy arn being based on aws partition data source. As I understand it, it's only dynamic due to the eks module needing to work inside AWS CN vs non-CN. 
A possible workaround (only available if you locally clone the eks module) is to statically hardcode the managed policy arns, if you are not operating in CN regions. I expect this would prevent the last part, which I think is hitting a possible IAM eventual consistency bug as described above. The theory is that if the arn doesnt change (static), it would not try to recompute and replace it.

**Comment by Pinolo** [comment]
Can confirm we're seeing the same behavior as @jrsdav. We have a dynamic value in `default_tags` property, but we also tested without it and every time the static default tags are updated, the policy attachment incident happens.

Interesting notes, @zerog2k! I think that the same problem could occur with CloudFormation, right? Unless it has implemented a workaround for eventual consistency.

**Comment by daroga0002** [comment]
which version of terraform and provider you using?

I would recommend to update both as there is a lot of improvements (especially in aws provider and `default_tags`)

**Comment by Pinolo** [comment]
> which version of terraform and provider you using?

TF: 1.0.3
AWS provider: 3.58.0
EKS module: 17.19.0

**Comment by zerog2k** [comment]
I was able to (unfortunately) reproduce one of the trigger behaviors - detach and reattach policy to role
moved from using `aws_iam_role_policy_attachment` to attach a managed policy to a role, to using `managed_policy_arns` attribute on `aws_iam_role` resource.
After running plan/apply on the first time, the plan looks correct, but the result is that the managed policy is detached from the role (unexpected).
Only on a second plan is it seen that the policy attachment is missing, and corrected in the corresponding apply phase.
Just fyi, as this seems to be the root cause or a main factor in the underlying aws provider implementation. (I am also observing this with latest hashicorp/aws v3.60.0 provider, fyi).

**Comment by autarchprinceps** [comment]
This is still an issue for us. Is there an actuall solution in this thread I am missing, outside of replacing this module with own code? Because to me this constantly breaks EKS in its entirety. Without EKS Policies, nodes no longer register and the entire cluster dies after a few scaling events or spot replacements.
