### ISSUE TITLE
Cannot Create a New Cluster w/ 17.21.0

### ISSUE THREAD

**Issue by onelapahead** [terraform-aws-modules/terraform-aws-eks#1635]
## Description

The module fails to create new clusters bc its trying to lookup an EKS cluster that does not exist by default.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: v1.0.7

 - Provider(s): 
  - hashicorp/aws v3.62.0  
- Module: v17.21.0

## Reproduction

Attempt to create an EKS cluster w/ node groups. For reference I'm using region `ap-southeast-2`.

### Code Snippet to Reproduce

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = "1.21"
  subnets         = module.vpc.private_subnets
  vpc_id          = module.vpc.vpc_id

  node_groups = {
    workers = {
      instance_types = [var.worker_instance_type]
      iam_role_arn = aws_iam_role.workers.arn
      desired_capacity = var.min_capacity
      max_capacity     = var.max_capacity
      min_capacity     = var.min_capacity

      launch_template_id      = aws_launch_template.default.id
      launch_template_version = aws_launch_template.default.default_version

      additional_tags = local.common_tags

      depends_on = [
        aws_iam_role_policy_attachment.workers-AmazonEKSWorkerNodePolicy,
        aws_iam_role_policy_attachment.workers-AmazonEKS_CNI_Policy,
        aws_iam_role_policy_attachment.workers-AmazonEC2ContainerRegistryReadOnly,
      ]
    }
  }
}
```

## Expected behavior

I can use this module to create an EKS cluster w/ node groups

## Actual behavior

It's failing to create a cluster w/ node groups bc it cannot find a default EKS cluster.

### Terminal Output Screenshot(s)

<img width="809" alt="Screen Shot 2021-10-12 at 12 01 25 PM" src="https://user-images.githubusercontent.com/11233384/136990526-f888b53b-042d-4d28-b8c8-48bb606ff125.png">

## Additional context

see https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1633#discussion_r727281750

**Comment by daroga0002** [comment]
@bengesoff @hfuss I checked and seems issue is occuring not during cluster creation but rather during `refresh` phase when new cluster code is added to existing  code.

Could you confirm?

**Comment by stevehipwell** [comment]
@daroga0002 I'll try and answer your points below.

It wouldn't be easy, if even possible, to pass the dynamic endpoint and CA into userdata for a non EKS optimised AMIs, which is why I added them as variables into the userdata template to be consumed by the custom userdata embedded below.

You are correct that _bootstrap.sh_ on an EKS optimised AMI **can** download these values itself, but I would rather they were passed in as happens by default to limit the moving parts and so nothing that can be generated in advance is left until runtime and done on each node. This is what we do for the other worker userdata so is consistent (MNGs do this too behind the scenes).

As far as the template goes; the first block either modifies _bootstrap.sh_ if we're getting a merged userdata because we didn't pass in an AMI ID, or it sets the variables without needing the modify _bootstrap.sh_ to source them from another file. Then we add the custom userdata. Finally we call _bootstrap.sh_ if we have an EKS optimised AMI that isn't going to merge the userdata. If you have a non-EKS optimised AMI your custom userdata needs to replicate _bootstrap.sh_ or your node wont join the cluster.

**Comment by cmsmith7** [comment]
Hi we are also now in a predicament whereby we are unable to deploy new clusters .. typically the update happened during some of our upgrades and testing.  Do you have an idea when we could expect this to be fixed? Many thanks.

**Comment by amahpour** [comment]
FYI, as a beginner to intermediate TF user I spent ~5 hours today trying to debug this issue. I, mistakenly, did not specify a version number when pulling this module (and verified that rolling back to **17.20.0** works perfectly). Additionally, this issue page hasn't been indexed yet on Google so searching for the output error will get you meek results (some referring to githubmemory.com which eventually got me here).

Just thought I'd add my two cents so we can make this PR a priority...

**Comment by antonbabenko** [comment]
@daroga0002 @stevehipwell Do you guys know when the fix will be ready?

**Comment by antonbabenko** [comment]
@stevehipwell I have just merged it and released [v17.22.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.22.0).

During the night I received even more emails from GitHub and didn't have a chance to read the one where Dawid mentioned me. Thank you very much for your contribution!

**Comment by daroga0002** [comment]
> @antonbabenko this one was on me so I'm glad I could help get it fixed. I'm still slightly unclear as to why using the data source failed in the way it did, but in hindsight the current solution was the one that I should have stuck with as it's significantly simpler to pass variables rather than re-fetch them.

As per me this is some terraform bug with dependencies during `refresh` phase as I also tried to setup that data source with explicit dependency defining somthing like:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/6b3a8e62379e4438df73ad18921805436d917482/modules/node_groups/main.tf#L105

but it was still failing
